linters-settings:
    dupl:
        threshold: 100
    exhaustive:
        default-signifies-exhaustive: false
    funlen:
        lines: 100
        statements: 50
    gci:
        local-prefixes: github.com/osvim/unit-of-work
    goconst:
        min-len: 2
        min-occurrences: 2
    gocritic:
        enabled-tags:
            - diagnostic
            - experimental
            - opinionated
            - performance
            - style
        disabled-checks:
            - dupImport # https://github.com/go-critic/go-critic/issues/845
            - ifElseChain
            - octalLiteral
            - whyNoLint
            - wrapperFunc
    gocyclo:
        min-complexity: 15
    goimports:
        local-prefixes: github.com/osvim/unit-of-work
    gomnd:
        settings:
            mnd:
                # don't include the "operation" and "assign"
                checks: argument,case,condition,return
    govet:
        enable-all: true
    lll:
        line-length: 140
    misspell:
        locale: US
    nolintlint:
        allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
        allow-unused: false # report any unused nolint directives
        require-explanation: false # don't require an explanation for nolint directives
        require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
    disable-all: true
    enable:
        - bodyclose
        - deadcode
        - depguard
        - dogsled
        - dupl
        - errcheck
        - exhaustive
        - funlen
        - goconst
        - gocritic
        - gocyclo
        - gofmt
        - goimports
        - revive
        - gomnd
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - lll
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - rowserrcheck
        - exportloopref
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace
        - prealloc
        - errorlint
        - nilerr

issues:
    # Excluding configuration per-path, per-linter, per-text and per-source
    exclude-rules:
        # not needed
        -   path: /*.go
            text: "ST1003: should not use underscores in package names"
            linters:
                - stylecheck
        -   path: /*.go
            text: "don't use an underscore in package name"
            linters:
                - revive
        -   path: context.go
            text: "ptrToRefParam: consider `err' to be of non-pointer type"
            linters:
                - gocritic
    exclude:
        - Using the variable on range scope `test` in function literal
run:
    skip-dirs:
        - vendor